# Generated by Django 5.0.14 on 2025-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0004_userresponse_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testregistration',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
