# Generated by Django 5.0.14 on 2025-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0005_testregistration_evaluated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
