# Generated by Django 5.0.14 on 2025-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0006_testregistration_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
