# Generated by Django 5.0.14 on 2025-11-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0007_testregistration_is_shortlisted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testregistration',
            options={'managed': False},
        ),
    ]
