# Generated by Django 5.0.14 on 2025-11-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0008_alter_testregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testregistration',
            options={'managed': True},
        ),
    ]
