# Generated by Django 5.0.14 on 2025-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0009_alter_testregistration_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testregistration',
            name='is_shortlisted',
        ),
        migrations.AlterField(
            model_name='testregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='testregistration',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
