# Generated by Django 5.0.14 on 2025-11-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0010_remove_testregistration_is_shortlisted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testregistration',
            name='score',
        ),
    ]
