# Generated by Django 5.0.14 on 2025-11-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0011_remove_testregistration_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testregistration',
            options={},
        ),
        migrations.AddField(
            model_name='testregistration',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testregistration',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testregistration',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
