# Generated by Django 5.0.14 on 2026-05-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0006_testregistration_is_shortlisted'),
        ('user_tests', '0012_alter_testregistration_options_and_more'),
    ]

    operations = [
    ]
