# Generated by Django 5.0.14 on 2026-05-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0013_merge_20260512_0730'),
    ]

    operations = [
    ]
