# Generated by Django 5.0.14 on 2026-05-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_recruitmentdrive_created_by_and_more'),
        ('user_tests', '0014_add_is_evaluated_evaluated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testregistration',
            name='question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.questionpaper'),
        ),
    ]
