# Generated by Django 5.0.14 on 2026-05-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0016_userresponse_evaluation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('url_at_time', models.CharField(blank=True, max_length=500, null=True)),
                ('tab_title', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='user_tests.testregistration')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
