# Generated by Django 5.0.14 on 2026-05-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0018_testregistration_camera_access_granted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testregistration',
            name='camera_access_granted',
        ),
        migrations.RemoveField(
            model_name='testregistration',
            name='proctoring_score',
        ),
        migrations.RemoveField(
            model_name='testregistration',
            name='total_violations',
        ),
        migrations.DeleteModel(
            name='TestViolation',
        ),
    ]
