# Generated by Django 5.0.14 on 2026-05-14 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0019_remove_testregistration_camera_access_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='camera_access_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testregistration',
            name='proctoring_score',
            field=models.FloatField(default=100.0, help_text='Trust percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='testregistration',
            name='total_violations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Blur'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('FACE_NOT_FOUND', 'Face Not Found'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('SCREEN_RECORDING_STOPPED', 'Screen Recording Stopped'), ('CAMERA_ACTIVE', 'Camera Activated'), ('CAMERA_DENIED', 'Camera Denied'), ('PERIODIC_CHECK', 'Periodic Identity Check')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds (if applicable)')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='proctoring/snapshots/')),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='proctoring/clips/')),
                ('description', models.TextField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='user_tests.testregistration')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
