# Generated by Django 5.0.14 on 2025-11-12 06:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_questionpaper_is_private_link_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='Which round is this test? (1, 2, 3...)'),
        ),
        migrations.CreateModel(
            name='RecruitmentDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Backend Developer Hiring - Jan 2025'", max_length=255)),
                ('position', models.CharField(help_text="Job role, e.g., 'Senior Backend Developer'", max_length=200)),
                ('description', models.TextField(help_text='Full job description')),
                ('total_positions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('filled_positions', models.PositiveIntegerField(default=0)),
                ('application_start_date', models.DateField()),
                ('application_end_date', models.DateField()),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('drive_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Applications'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('auto_close_on_full', models.BooleanField(default=True)),
                ('drive_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public_link_active', models.BooleanField(default=False)),
                ('link_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('require_test', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('test_papers', models.ManyToManyField(blank=True, related_name='linked_drives', to='app.questionpaper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='recruitment_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_rounds', to='app.recruitmentdrive'),
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=255)),
                ('current_stage', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Under Screening'), ('ROUND_1', 'Round 1 (Test)'), ('ROUND_2', 'Round 2 (Interview)'), ('FINAL_ROUND', 'Final Round'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20)),
                ('overall_status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('all_tests_completed', models.BooleanField(default=False)),
                ('aggregate_score', models.FloatField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('stage_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_updates', to=settings.AUTH_USER_MODEL)),
                ('recruitment_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.recruitmentdrive')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('recruitment_drive', 'email')},
            },
        ),
    ]
