# Generated by Django 5.0.14 on 2025-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_papersection_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weightage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
