# Generated by Django 5.0.14 on 2026-05-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile_profile_image'),
        ('recruitment', '0010_jobround'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_interview_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='job_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='job_type',
            field=models.CharField(blank=True, default='Full-time', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='pay_scale',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='positions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='recruitment_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.jobpost'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='round_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='rounds',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
