# Generated by Django 5.0.14 on 2025-11-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_questionpaper_round_number_recruitmentdrive_and_more'),
        ('app', '0018_question_weightage'),
    ]

    operations = [
    ]
