# Generated by Django 5.0.14 on 2025-11-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20251120_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='created_by',
        ),
    ]
