# Generated by Django 5.0.14 on 2025-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_questionpaper_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='job_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
