# Generated by Django 5.0.14 on 2025-11-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_questionpaper_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_interview_round',
            field=models.BooleanField(default=False, help_text='True if this is an Interview Round (no auto-assessment)'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='pay_scale',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='rounds',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='job_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
