# Generated by Django 5.0.14 on 2025-11-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_questionpaper_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='is_interview_round',
        ),
    ]
