# Generated by Django 5.0.14 on 2025-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_questionpaper_is_interview_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_interview_round',
            field=models.BooleanField(default=False, help_text='True if this is an Interview Round (no auto-assessment)'),
        ),
    ]
