# Generated by Django 5.0.14 on 2025-11-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_questionpaper_is_interview_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='current_ctc_rate',
            field=models.CharField(blank=True, help_text='Unit for Current CTC (e.g., LPA, PM)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='expected_ctc_rate',
            field=models.CharField(blank=True, help_text='Unit for Expected CTC (e.g., LPA, PM)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='is_experienced',
            field=models.BooleanField(default=False, help_text='True if candidate is Experienced (based on candidateType radio button)'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='linked_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_received', to='app.questionpaper'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='photo_file',
            field=models.FileField(blank=True, help_text='Candidate Photo', null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='referral_source',
            field=models.CharField(blank=True, help_text='From where did you hear about us?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='skills',
            field=models.TextField(blank=True, help_text='Your Skills (comma separated)', null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='total_experience',
            field=models.FloatField(blank=True, help_text='Total years of experience (0 for Fresher)', null=True),
        ),
    ]
