# Generated by Django 5.0.14 on 2025-11-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_candidateapplication_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='recruitment_drive',
        ),
    ]
