# Generated by Django 5.0.14 on 2025-11-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_candidateapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='recruitment_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.recruitmentdrive'),
        ),
    ]
