# Generated by Django 5.0.14 on 2026-05-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_questionpaper_end_date_and_more'),
        ('app', '0028_candidateapplication_recruitment_drive'),
    ]

    operations = [
    ]
