# Generated by Django 5.0.14 on 2025-12-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_candidateapplication_recruitment_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text="True for static rounds like 'Assessment Test'.")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
