# Generated by Django 5.0.14 on 2025-12-01 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_round'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(help_text="e.g., 'Group Discussion', 'Technical Interview (R1)', 'HR Interview (Final)'", max_length=100)),
                ('score', models.IntegerField(blank=True, help_text='Overall score out of 100 or a specific scale.', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Detailed feedback on performance.')),
                ('is_passed', models.BooleanField(default=False)),
                ('communication_score', models.PositiveIntegerField(default=0)),
                ('domain_knowledge_score', models.PositiveIntegerField(default=0)),
                ('leadership_score', models.PositiveIntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_application', models.ForeignKey(help_text='The application being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.candidateapplication')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
