# Generated by Django 5.0.14 on 2026-05-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_merge_20260512_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentdrive',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recruitmentdrive',
            name='department',
        ),
        migrations.RemoveField(
            model_name='recruitmentdrive',
            name='test_papers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='weightage',
        ),
        migrations.DeleteModel(
            name='CandidateApplication',
        ),
        migrations.DeleteModel(
            name='RecruitmentDrive',
        ),
    ]
