"""
Django settings for project_name project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# PRODUCTION SETTINGS
# -----------------------------
SECRET_KEY = os.environ.get("SECRET_KEY", "your-secret-key")
DEBUG = False

# Render domain add karein (IMPORTANT)
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "ai-written-test-5tny.onrender.com",
]

# -----------------------------
# INSTALLED APPS
# -----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "app",
    "user_tests",
    "widget_tweaks",
]

# -----------------------------
# MIDDLEWARE
# -----------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",    # Render static fix
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ai_test.urls"

# -----------------------------
# TEMPLATES
# -----------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ai_test.wsgi.application"

# -----------------------------
# EMAIL SETTINGS
# -----------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "shweta.ladne.averybit@gmail.com"
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD")   # safer

# -----------------------------
# DATABASE (Render)
# -----------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "written_test_ydbx",
        "USER": "written_test_ydbx_user",
        "PASSWORD": "9DDegu2JdEFSW9Qw5MiTcLCZT1Mqh690",
        "HOST": "dpg-d4arav9e2q1c73b72klg-a.oregon-postgres.render.com",
        "PORT": "5432",
        "OPTIONS": {"sslmode": "require"},
    }
}

# -----------------------------
# OPENAI / GEMINI API KEYS
# -----------------------------
env = environ.Env(
    GEMINI_API_KEY=(str, ""),
    OPENAI_API_KEY=(str, "")
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

GEMINI_API_KEY = env("GEMINI_API_KEY")
OPENAI_API_KEY = env("OPENAI_API_KEY")

print(f"DEBUG: OpenAI Key Loaded: {'Yes' if OPENAI_API_KEY else 'No'}")

# -----------------------------
# INTERNATIONALIZATION
# -----------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------
# STATIC FILES (Render fix)
# -----------------------------
STATIC_URL = "/static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Render requires STATIC_ROOT
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
